INSERT INTO product (name, price, category) VALUES
                                                ('Mleko 3.2%', 3.50, 'nabial'),
                                                ('Chleb pełnoziarnisty', 4.20, 'pieczywo'),
                                                ('Masło 200g', 7.90, 'nabial'),
                                                ('Szynka konserwowa', 12.80, 'mieso'),
                                                ('Ser żółty', 9.40, 'nabial'),
                                                ('Bułka pszenna', 1.00, 'pieczywo'),
                                                ('Kiełbasa wiejska', 14.90, 'mieso'),
                                                ('Bagietka francuska', 2.80, 'pieczywo'),
                                                ('Jogurt naturalny', 2.50, 'nabial'),
                                                ('Sok pomarańczowy 1L', 4.60, 'napoje'),
                                                ('Woda niegazowana 1.5L', 2.10, 'napoje'),
                                                ('Cola 1.25L', 5.00, 'napoje'),
                                                ('Filet z kurczaka', 18.00, 'mieso'),
                                                ('Chleb razowy', 3.90, 'pieczywo'),
                                                ('Twarożek wiejski', 3.70, 'nabial'),
                                                ('Pasztet drobiowy', 4.30, 'mieso'),
                                                ('Sok jabłkowy 1L', 4.20, 'napoje'),
                                                ('Herbata czarna 100g', 6.50, 'inne'),
                                                ('Cukier biały 1kg', 4.00, 'inne'),
                                                ('Makaron penne 500g', 3.20, 'inne');
